### ISSUE TITLE
find_package(Stb REQUIRED)

### ISSUE THREAD

**Issue by MINGUOLIU** [heyManNice/EasyMusic#2]
[{
	"resource": "/C:/Users/feixiang/Desktop/project/EasyMusic/CMakeLists.txt",
	"owner": "cmake-configure-diags",
	"severity": 8,
	"message": "CMake Error at CMakeLists.txt:11 (find_package):By not providing \"FindStb.cmake\" in CMAKE_MODULE_PATH this project has\nasked CMake to find a package configuration file provided by \"Stb\", but\nCMake did not find one.\n\nCould not find a package configuration file provided by \"Stb\" with any of\nthe following names:\n\n  StbConfig.cmake\n  stb-config.cmake\n\nAdd the installation prefix of \"Stb\" to CMAKE_PREFIX_PATH or set \"Stb_DIR\"\nto a directory containing one of the above files.  If \"Stb\" provides a\nseparate development package or SDK, be sure it has been installed.",
	"source": "CMake (find_package)",
	"startLineNumber": 11,
	"startColumn": 1,
	"endLineNumber": 11,
	"endColumn": 10000
}]
cmake找不到"Stb"包的配置文件，这个问题怎么解决

**Comment by heyManNice** [comment]
我不了解。可能后续有其他人可以帮你解答这个问题。
但是如果你需要编译的话可以查看这个链接中的方案，这也是我打算使用的新方案。
https://github.com/heyManNice/EasyMusic/issues/3
