### ISSUE TITLE
字符乱码

### ISSUE THREAD

**Issue by systemannounce** [heyManNice/EasyMusic#5]
如果使用系统utf-8软件就会乱码。
![image](https://github.com/heyManNice/EasyMusic/assets/55303494/304fdac4-a911-4ebf-8000-2a4af19955d1)

**Comment by heyManNice** [comment]
对的，目前除了tooltip(鼠标停留的悬浮框)之外，其余字符都使用GBK字符集。后续会逐一修改为utf-8
